name = "MolHamLinAlg"
uuid = "5c8b6b33-8701-41e8-be2b-ae5d6cb070f9"
authors = ["lucyhao <hao.lucyy@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
LinearAlgebra = "1.11.0"
PyCall = "1.96.4"
Tullio = "0.3.8"
